library(dplyr)
house1 <- read.csv2("household_power_consumption.txt", na.strings = "?")
house <- filter(house1,   house1$Date == "1/2/2007"| house1$Date == "2/2/2007")
house$Sub_metering_1<-unlist(lapply(house$Sub_metering_1, as.numeric)
                             , use.names = TRUE)
house$Sub_metering_2<-unlist(lapply(house$Sub_metering_2, as.numeric)
                             , use.names = TRUE)
house$Sub_metering_3<-unlist(lapply(house$Sub_metering_3, as.numeric)
                             , use.names = TRUE)
house$Voltage<-unlist(lapply(house$Voltage, as.numeric)
                             , use.names = TRUE)
house$Global_reactive_power<-unlist(lapply(house$Global_reactive_power, as.numeric)
                                  , use.names = TRUE)
datetime <-select(house, Date:Time)
datetime <- strptime(paste(datetime$Date, datetime$Time, sep = " "), "%d/%m/%Y %H:%M:%S")
png("plot4.png", width = 480, height = 480)
par(mfrow = c(2, 2))
plot(datetime, house$Global_active_power, type = "l", xlab = "", ylab = "Global Active power" )
plot(datetime, house$Voltage, type = "l", xlab = "datetime", ylab = "Voltage" )
plot(datetime, house$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering", col = "black", ylim = c(0, 40)) 
par(new=TRUE)
plot(datetime, house$Sub_metering_2, type = "l", xlab = "", ylab = "", col = "red", ylim = c(0, 40)) 
par(new=TRUE)
plot(datetime, house$Sub_metering_3, type = "l", xlab = "", ylab = "", col = "blue", ylim = c(0, 40)) 
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black","red","blue"))
plot(datetime, house$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power" )
dev.off()
