library(dplyr)
house1 <- read.csv2("household_power_consumption.txt", na.strings = "?")
house <- filter(house1,   house1$Date == "1/2/2007"| house1$Date == "2/2/2007")
house$Global_active_power<-unlist(lapply(house$Global_active_power, as.numeric)
                                  , use.names = TRUE)
datetime <-select(house, Date:Time)
datetime <- strptime(paste(datetime$Date, datetime$Time, sep = " "), "%d/%m/%Y %H:%M:%S")
png("plot2.png", width = 480, height = 480)
plot(datetime, house$Global_active_power, type = "l", xlab = "", ylab = "Global Active power (kilowatts)" )
dev.off()