library(dplyr)
house1 <- read.csv2("household_power_consumption.txt", na.strings = "?")
house <- filter(house1,   house1$Date == "1/2/2007"| house1$Date == "2/2/2007")
house$Sub_metering_1<-unlist(lapply(house$Sub_metering_1, as.numeric)
                                  , use.names = TRUE)
house$Sub_metering_2<-unlist(lapply(house$Sub_metering_2, as.numeric)
                             , use.names = TRUE)
house$Sub_metering_3<-unlist(lapply(house$Sub_metering_3, as.numeric)
                             , use.names = TRUE)
datetime <-select(house, Date:Time)
datetime <- strptime(paste(datetime$Date, datetime$Time, sep = " "), "%d/%m/%Y %H:%M:%S")

png("plot3.png", width = 480, height = 480)
plot(datetime, house$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering", col = "black", ylim = c(0, 40)) 
par(new=TRUE)
plot(datetime, house$Sub_metering_2, type = "l", xlab = "", ylab = "", col = "red", ylim = c(0, 40)) 
par(new=TRUE)
plot(datetime, house$Sub_metering_3, type = "l", xlab = "", ylab = "", col = "blue", ylim = c(0, 40)) 
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black","red","blue"))
dev.off()